version: '3.9'

services:
  node:
    build: .
    environment:
      - PORT=${PORT}
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - ./src:/usr/src/app/src
      - ./logs:/usr/src/app/src/logs
    container_name: node
    networks:
      - app_network
    restart: unless-stopped
    command: npm start
  postgres:
    restart: always
    image: postgres:9.6.24-alpine3.15
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  data:
  logs:
